version: "3.1"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hexagonal
    ports:
      - "5432:5432"